# Generated by Django 3.1.6 on 2021-03-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=61)),
                ('truck_year', models.IntegerField()),
                ('mileage_in_km', models.IntegerField()),
                ('mileage_in_mp', models.IntegerField()),
                ('location', models.CharField(max_length=99)),
                ('price', models.IntegerField(default=0)),
                ('photo_url', models.CharField(max_length=150)),
                ('HP', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('fuel_tank', models.IntegerField()),
                ('lifting_capacity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trucks.truck_card')),
            ],
        ),
    ]
