# Generated by Django 3.1.6 on 2021-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_card',
            name='mileage_in_mp',
        ),
        migrations.RemoveField(
            model_name='truck_card',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='truck_card',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
