# Generated by Django 3.1.6 on 2021-03-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20210307_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_card',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
