# Generated by Django 3.1.6 on 2021-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_auto_20210307_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_card',
            name='price',
            field=models.IntegerField(),
        ),
    ]
