# Generated by Django 3.1.6 on 2021-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_auto_20210308_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_card',
            name='photo',
            field=models.CharField(max_length=100),
        ),
    ]
