# Generated by Django 3.1.6 on 2021-03-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0006_auto_20210310_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_card',
            name='photo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
