# Generated by Django 3.1.6 on 2021-03-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0007_auto_20210310_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_card',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
