# Generated by Django 3.1.6 on 2021-03-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0008_auto_20210310_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_card',
            name='mail',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='truck_card',
            name='phone',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
