# Generated by Django 3.1.6 on 2021-03-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0009_auto_20210311_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck_card',
            old_name='phone',
            new_name='ph0ne',
        ),
    ]
