# Generated by Django 3.1.6 on 2021-03-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0010_auto_20210311_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_card',
            name='ph0ne',
            field=models.IntegerField(),
        ),
    ]
