# Generated by Django 3.1.6 on 2021-03-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0011_auto_20210311_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_card',
            name='ph0ne',
        ),
        migrations.AddField(
            model_name='truck_card',
            name='phone_number',
            field=models.IntegerField(default='0'),
        ),
    ]
