# Generated by Django 3.1.6 on 2021-03-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0012_auto_20210311_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_card',
            name='phone_number',
            field=models.IntegerField(default=380),
        ),
    ]
