# Generated by Django 3.1.6 on 2021-03-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0013_auto_20210311_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_card',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='truck_card',
            name='phone_number',
        ),
    ]
