# Generated by Django 3.1.6 on 2021-03-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0014_auto_20210311_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_card',
            name='mail',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='truck_card',
            name='phone',
            field=models.IntegerField(default='380'),
        ),
    ]
