# Generated by Django 3.1.6 on 2021-03-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0015_auto_20210311_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_card',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='truck_card',
            name='phone',
        ),
    ]
