# Generated by Django 3.1.6 on 2021-03-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0017_auto_20210311_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_card',
            name='phone',
            field=models.IntegerField(default=380),
        ),
    ]
